#!/bin/bash
set -xeuo pipefail

python depsBundle.py

rm -f dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps-windows.zip
rm -f dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps-linux.zip
rm -f dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps-macos-intel.zip
rm -f dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps-macos-arm64.zip

mv dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps_win_amd64.zip dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps-windows.zip
mv dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps_manylinux2014_x86_64.zip dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps-linux.zip
mv dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps_macosx_10_9_x86_64.zip dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps-macos-intel.zip
mv dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps_macosx_11_0_arm64.zip dependency_bundle/deadline_cloud_for_cinema_4d_submitter-deps-macos-arm64.zip
