site_name: Cinema 4D + AWS Deadline Cloud
site_description: Render Cinema 4D scenes in the cloud with AWS Deadline Cloud
site_url: https://{{ github.repository_owner }}.github.io/{{ github.event.repository.name }}/
repo_url: https://github.com/{{ github.repository }}
repo_name: {{ github.repository }}

theme:
  name: material
  palette:
    - scheme: default
      primary: orange
      accent: orange
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share

copyright: Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

docs_dir: docs/user_guide

nav:
  - Home: index.md
  - Quick Start: getting-started.md
  - Submitter Features: submitter-features.md

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search

extra_css:
  - stylesheets/extra.css